### PR TITLE
Let user script accept firstname, surname and password too

### PR DESCRIPTION
**Pull request by pwalczysko**
@joshmoore 

This PR tries to improve the ``user`` script so that it 

   1. accepts firstname, surname and password of the newly created ldap user, which will then appear in OMERO (tested on outreach)
   2. has an output which warns when something goes wrong (see the end of the script) and a suggestion about how to style the ``./user.... add`` command

Please feel free to reject, there is a following drawback in this suggestion:

  - I have added three ``shifts`` to the script to cater for the enriched input, which is fine for the ``add`` command. This causes the other commands (``./group`` for example) to now demand the input in the form of ``loginname firstname surname password`` as well, which is of course undesirable.

Any suggestions welcome. Thank you

### CODE REVIEW

**Comment by joshmoore** [comment]
Can you update `.travis.yml` so that the PR is green?

Re: the bash arguments, I was again really quite lazy. cF. https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash

**Comment by pwalczysko** [comment]
Travis fixed @joshmoore

**Comment by joshmoore** [comment]
The changes are correct, but I worry that the more `shift`s we add here, the harder it's going to get to manage these. Please see my attempt at a rewrite in `ldapo`.

**Comment by pwalczysko** [comment]
np, thank you

**Pull request closed without merging**
